name: Run Linter

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      deno-version: lts

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4

      - name: 'Setup Deno'
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: ${{env.deno-version}}
      
      - name: 'Run Linter'
        run: deno task lint
